# Do not forget to create the .env file (see template)
# before using this container!

version: '2'

services:
    # see https://hub.docker.com/_/redmine/
    redmine:
        image: redmine:3.4.4
        restart: always
        environment:
            REDMINE_DB_MYSQL: db
            REDMINE_DB_PASSWORD: example
        ports:
            - 9001:9002

    # see https://hub.docker.com/_/mysql/
    redmine_db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
        volumes:
            - ./backups:/tmp/backups
